/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "control.pb-c.h"
void   controller_state__init
                     (ControllerState         *message)
{
  static ControllerState init_value = CONTROLLER_STATE__INIT;
  *message = init_value;
}
size_t controller_state__get_packed_size
                     (const ControllerState *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controller_state__pack
                     (const ControllerState *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controller_state__pack_to_buffer
                     (const ControllerState *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControllerState *
       controller_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControllerState *)
     protobuf_c_message_unpack (&controller_state__descriptor,
                                allocator, len, data);
}
void   controller_state__free_unpacked
                     (ControllerState *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   controller_back__init
                     (ControllerBack         *message)
{
  static ControllerBack init_value = CONTROLLER_BACK__INIT;
  *message = init_value;
}
size_t controller_back__get_packed_size
                     (const ControllerBack *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_back__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controller_back__pack
                     (const ControllerBack *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_back__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controller_back__pack_to_buffer
                     (const ControllerBack *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_back__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControllerBack *
       controller_back__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControllerBack *)
     protobuf_c_message_unpack (&controller_back__descriptor,
                                allocator, len, data);
}
void   controller_back__free_unpacked
                     (ControllerBack *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &controller_back__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor controller_state__field_descriptors[2] =
{
  {
    "Ctrl_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ControllerState, ctrl_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ctrl_state",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ControllerState, ctrl_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controller_state__field_indices_by_name[] = {
  0,   /* field[0] = Ctrl_id */
  1,   /* field[1] = Ctrl_state */
};
static const ProtobufCIntRange controller_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor controller_state__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Controller_state",
  "ControllerState",
  "ControllerState",
  "",
  sizeof(ControllerState),
  2,
  controller_state__field_descriptors,
  controller_state__field_indices_by_name,
  1,  controller_state__number_ranges,
  (ProtobufCMessageInit) controller_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor controller_back__field_descriptors[3] =
{
  {
    "Ctrl_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ControllerBack, ctrl_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ctrl_state",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ControllerBack, ctrl_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ctrl_success",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ControllerBack, ctrl_success),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controller_back__field_indices_by_name[] = {
  0,   /* field[0] = Ctrl_id */
  1,   /* field[1] = Ctrl_state */
  2,   /* field[2] = Ctrl_success */
};
static const ProtobufCIntRange controller_back__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor controller_back__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Controller_back",
  "ControllerBack",
  "ControllerBack",
  "",
  sizeof(ControllerBack),
  3,
  controller_back__field_descriptors,
  controller_back__field_indices_by_name,
  1,  controller_back__number_ranges,
  (ProtobufCMessageInit) controller_back__init,
  NULL,NULL,NULL    /* reserved[123] */
};
